describe('template prueba juice shop', () => {
  it('passes', () => {
    const email = `simon_${Date.now()}@test.com`
    cy.visit('http://localhost:3000/#/')

    cy.get('.cc-btn', { timeout: 10000 })
      .should('be.visible')
      .click()

    cy.get('.cc-window').should('not.be.visible')

    cy.contains('Dismiss')
      .should('be.visible')
      .click()

    cy.get('#navbarAccount > .mdc-button__label > span').click()
    cy.get('.mat-mdc-menu-item-text > span').click()
    cy.wait(1000)
    cy.get('#newCustomerLink > .primary-link').click()
    cy.get('#registration-form > :nth-child(1) > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').type(email)
    cy.get('#registration-form > :nth-child(2) > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').type('12345')
    cy.get('#repeatPasswordControl').type('12345')
    cy.get('.mat-mdc-form-field-type-mat-select > .mat-mdc-text-field-wrapper > .mat-mdc-form-field-flex > .mat-mdc-form-field-infix').click()
    cy.get('#mat-option-4 > .mdc-list-item__primary-text').click()
    cy.get('#securityAnswerControl').type('Juice Shop')
    cy.get('#registerButton > .mdc-button__label').click()
    cy.get('[name="email"]').type(email)
    cy.get('[name="password"]').type('12345')
    cy.get('#rememberMe-input').click()
    cy.get('#loginButton > .mdc-button__label').click()
    cy.get('.mdc-button.ng-star-inserted > .mdc-button__label > .hide-lt-md').should('be.visible')
    cy.get('#navbarAccount > .mdc-button__label > span').click()
    cy.wait(1000)
    cy.get('.mat-mdc-menu-content > [aria-label="Show Privacy and Security Menu"]').click()
    cy.get('[aria-label="Go to change password page"] > .mat-mdc-menu-item-text > span').click()
    cy.get('#mat-mdc-form-field-label-13 > mat-label').type('12345')
    cy.get('#newPassword').type('54321')
    cy.get('#mat-mdc-form-field-label-15 > mat-label').type('54321')
    cy.get('#changeButton > .mdc-button__label').click()
    cy.get('.confirmation').should('be.visible')
  })
})